# Generated by Django 4.1.3 on 2022-11-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(1, 'manager'), (2, 'worker'), (3, 'Customer')], default=3)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
