# Generated by Django 4.1.3 on 2022-11-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.IntegerField(default=0, verbose_name=((1, 'Photographic products'), (2, 'Writing Tools'))),
            preserve_default=False,
        ),
    ]
